name: Deploy to SPF Server

on:
  push:
    branches: [ master ]

  workflow_run:
    workflows: ["Normalize wiki MD"]
    types:
      - completed

jobs:
  deploy:
    if: >
      (
        github.event_name == 'push'
      ) || (
        github.event_name == 'workflow_run' &&
        github.event.workflow_run.conclusion == 'success' &&
        github.event.workflow_run.head_branch == 'master'
      )
    runs-on: ubuntu-latest

    steps:
      - name: Run deploy script on server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SPF_HOST }}
          username: ${{ secrets.SPF_USER }}
          key: ${{ secrets.SPF_SSH_KEY }}
          script: |
            cd /root/spf/wiki/
            touch MAINTENANCE

            sudo systemctl stop spf-wiki.service

            git fetch origin master
            git reset --hard origin/master

            chmod -R o+rX static

            sudo systemctl start spf-wiki.service

            rm -f MAINTENANCE
